name: japanese_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  collection: ^1.18.0
  json_annotation: ^4.9.0
  simple_animations: ^5.0.2
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

assets:
   - assets/data/hiragana.json
   - assets/data/katakana.json
   - assets/data/kanji.json
   - assets/images/bgwelcome.png
   - assets/images/iconka.png
   - assets/images/iconhi.png
